ALTER TABLE tasks
    ADD COLUMN request_id VARCHAR(64) NULL,
    ADD COLUMN billing_request_id BIGINT NULL,
    ADD COLUMN upstream_task_id VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN submit_attempt INT NOT NULL DEFAULT 1,
    ADD COLUMN upstream_status VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN billing_status VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN upstream_result_persisted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN price_snapshot_persisted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN billing_snapshot TEXT NULL,
    ADD COLUMN usage_total BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN usage_available BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN usage_estimated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN usage_basis VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN usage_wait_until BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN final_quota BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN final_quota_determined BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN billing_last_error TEXT NULL,
    ADD COLUMN usage_accounted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN locked_by VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN locked_until BIGINT NOT NULL DEFAULT 0,
    ADD UNIQUE INDEX idx_tasks_request_id (request_id),
    ADD UNIQUE INDEX idx_tasks_billing_request_id (billing_request_id),
    ADD INDEX idx_tasks_upstream_task_id (upstream_task_id),
    ADD INDEX idx_tasks_upstream_billing (upstream_status, billing_status),
    ADD INDEX idx_tasks_usage_wait_until (usage_wait_until),
    ADD INDEX idx_tasks_locked_until (locked_until);

ALTER TABLE midjourneys
    ADD COLUMN request_id VARCHAR(64) NULL,
    ADD COLUMN billing_request_id BIGINT NULL,
    ADD COLUMN upstream_status VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN billing_status VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN upstream_result_persisted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN price_snapshot_persisted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN final_quota BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN final_quota_determined BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN billing_last_error TEXT NULL,
    ADD COLUMN usage_accounted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN locked_by VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN locked_until BIGINT NOT NULL DEFAULT 0,
    ADD UNIQUE INDEX idx_midjourneys_request_id (request_id),
    ADD UNIQUE INDEX idx_midjourneys_billing_request_id (billing_request_id),
    ADD INDEX idx_midjourneys_upstream_billing (upstream_status, billing_status),
    ADD INDEX idx_midjourneys_locked_until (locked_until);

CREATE TABLE IF NOT EXISTS sandbox_executions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    day VARCHAR(8) NOT NULL,
    ordinal INT NOT NULL,
    is_free BOOLEAN NOT NULL,
    quota BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY idx_sandbox_executions_request_id (request_id),
    KEY idx_sandbox_executions_user_day (user_id, day),
    KEY idx_sandbox_executions_status_created (status, created_at)
);
