CREATE TABLE IF NOT EXISTS billing_ledgers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    operation_key VARCHAR(128) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    funding_source VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    token_id BIGINT NOT NULL DEFAULT 0,
    amount BIGINT NOT NULL,
    wallet_before BIGINT NOT NULL,
    wallet_after BIGINT NOT NULL,
    token_remain_before BIGINT NOT NULL DEFAULT 0,
    token_remain_after BIGINT NOT NULL DEFAULT 0,
    token_used_before BIGINT NOT NULL DEFAULT 0,
    token_used_after BIGINT NOT NULL DEFAULT 0,
    token_unlimited BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY idx_billing_ledgers_operation_key (operation_key),
    KEY idx_billing_ledgers_request_id (request_id),
    KEY idx_billing_ledgers_operation (operation),
    KEY idx_billing_ledgers_funding_source (funding_source),
    KEY idx_billing_ledgers_user_id (user_id),
    KEY idx_billing_ledgers_token_id (token_id),
    KEY idx_billing_ledgers_created_at (created_at)
);
