CREATE TABLE IF NOT EXISTS billing_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    funding_source VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    token_id BIGINT NOT NULL DEFAULT 0,
    subscription_id BIGINT NOT NULL DEFAULT 0,
    token_unlimited BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL,
    reserved_quota BIGINT NOT NULL DEFAULT 0,
    actual_quota BIGINT NOT NULL DEFAULT 0,
    refunded_quota BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY idx_billing_requests_request_id (request_id),
    KEY idx_billing_requests_funding_source (funding_source),
    KEY idx_billing_requests_user_id (user_id),
    KEY idx_billing_requests_token_id (token_id),
    KEY idx_billing_requests_subscription_id (subscription_id),
    KEY idx_billing_requests_status (status),
    KEY idx_billing_requests_updated_at (updated_at)
);

CREATE TABLE IF NOT EXISTS billing_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    operation_key VARCHAR(128) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    target_quota BIGINT NOT NULL DEFAULT 0,
    attempts INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 10,
    next_retry_at BIGINT NOT NULL DEFAULT 0,
    locked_by VARCHAR(128) NOT NULL DEFAULT '',
    locked_until BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    completed_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY idx_billing_jobs_operation_key (operation_key),
    KEY idx_billing_jobs_request_id (request_id),
    KEY idx_billing_jobs_operation_type (operation_type),
    KEY idx_billing_jobs_scan (status, next_retry_at),
    KEY idx_billing_jobs_locked_until (locked_until)
);
